/** List of countries with full-name, country code, ISO country code (both 2 & 3 character) */
export const COUNTRIES = /* @__PURE__ */ Object.freeze([
	{
		country_name: 'Afghanistan',
		country_code: '93',
		iso_code_short: 'AF',
		iso_code: 'AFG',
	},
	{
		country_name: 'Albania',
		country_code: '355',
		iso_code_short: 'AL',
		iso_code: 'ALB',
	},
	{
		country_name: 'Algeria',
		country_code: '213',
		iso_code_short: 'DZ',
		iso_code: 'DZA',
	},
	{
		country_name: 'American Samoa',
		country_code: '1-684',
		iso_code_short: 'AS',
		iso_code: 'ASM',
	},
	{
		country_name: 'Andorra',
		country_code: '376',
		iso_code_short: 'AD',
		iso_code: 'AND',
	},
	{
		country_name: 'Angola',
		country_code: '244',
		iso_code_short: 'AO',
		iso_code: 'AGO',
	},
	{
		country_name: 'Anguilla',
		country_code: '1-264',
		iso_code_short: 'AI',
		iso_code: 'AIA',
	},
	{
		country_name: 'Antarctica',
		country_code: '672',
		iso_code_short: 'AQ',
		iso_code: 'ATA',
	},
	{
		country_name: 'Antigua and Barbuda',
		country_code: '1-268',
		iso_code_short: 'AG',
		iso_code: 'ATG',
	},
	{
		country_name: 'Argentina',
		country_code: '54',
		iso_code_short: 'AR',
		iso_code: 'ARG',
	},
	{
		country_name: 'Armenia',
		country_code: '374',
		iso_code_short: 'AM',
		iso_code: 'ARM',
	},
	{
		country_name: 'Aruba',
		country_code: '297',
		iso_code_short: 'AW',
		iso_code: 'ABW',
	},
	{
		country_name: 'Australia',
		country_code: '61',
		iso_code_short: 'AU',
		iso_code: 'AUS',
	},
	{
		country_name: 'Austria',
		country_code: '43',
		iso_code_short: 'AT',
		iso_code: 'AUT',
	},
	{
		country_name: 'Azerbaijan',
		country_code: '994',
		iso_code_short: 'AZ',
		iso_code: 'AZE',
	},
	{
		country_name: 'Bahamas',
		country_code: '1-242',
		iso_code_short: 'BS',
		iso_code: 'BHS',
	},
	{
		country_name: 'Bahrain',
		country_code: '973',
		iso_code_short: 'BH',
		iso_code: 'BHR',
	},
	{
		country_name: 'Bangladesh',
		country_code: '880',
		iso_code_short: 'BD',
		iso_code: 'BGD',
	},
	{
		country_name: 'Barbados',
		country_code: '1-246',
		iso_code_short: 'BB',
		iso_code: 'BRB',
	},
	{
		country_name: 'Belarus',
		country_code: '375',
		iso_code_short: 'BY',
		iso_code: 'BLR',
	},
	{
		country_name: 'Belgium',
		country_code: '32',
		iso_code_short: 'BE',
		iso_code: 'BEL',
	},
	{
		country_name: 'Belize',
		country_code: '501',
		iso_code_short: 'BZ',
		iso_code: 'BLZ',
	},
	{
		country_name: 'Benin',
		country_code: '229',
		iso_code_short: 'BJ',
		iso_code: 'BEN',
	},
	{
		country_name: 'Bermuda',
		country_code: '1-441',
		iso_code_short: 'BM',
		iso_code: 'BMU',
	},
	{
		country_name: 'Bhutan',
		country_code: '975',
		iso_code_short: 'BT',
		iso_code: 'BTN',
	},
	{
		country_name: 'Bolivia',
		country_code: '591',
		iso_code_short: 'BO',
		iso_code: 'BOL',
	},
	{
		country_name: 'Bosnia and Herzegovina',
		country_code: '387',
		iso_code_short: 'BA',
		iso_code: 'BIH',
	},
	{
		country_name: 'Botswana',
		country_code: '267',
		iso_code_short: 'BW',
		iso_code: 'BWA',
	},
	{
		country_name: 'Brazil',
		country_code: '55',
		iso_code_short: 'BR',
		iso_code: 'BRA',
	},
	{
		country_name: 'British Indian Ocean Territory',
		country_code: '246',
		iso_code_short: 'IO',
		iso_code: 'IOT',
	},
	{
		country_name: 'British Virgin Islands',
		country_code: '1-284',
		iso_code_short: 'VG',
		iso_code: 'VGB',
	},
	{
		country_name: 'Brunei',
		country_code: '673',
		iso_code_short: 'BN',
		iso_code: 'BRN',
	},
	{
		country_name: 'Bulgaria',
		country_code: '359',
		iso_code_short: 'BG',
		iso_code: 'BGR',
	},
	{
		country_name: 'Burkina Faso',
		country_code: '226',
		iso_code_short: 'BF',
		iso_code: 'BFA',
	},
	{
		country_name: 'Burundi',
		country_code: '257',
		iso_code_short: 'BI',
		iso_code: 'BDI',
	},
	{
		country_name: 'Cambodia',
		country_code: '855',
		iso_code_short: 'KH',
		iso_code: 'KHM',
	},
	{
		country_name: 'Cameroon',
		country_code: '237',
		iso_code_short: 'CM',
		iso_code: 'CMR',
	},
	{
		country_name: 'Canada',
		country_code: '1',
		iso_code_short: 'CA',
		iso_code: 'CAN',
	},
	{
		country_name: 'Cape Verde',
		country_code: '238',
		iso_code_short: 'CV',
		iso_code: 'CPV',
	},
	{
		country_name: 'Cayman Islands',
		country_code: '1-345',
		iso_code_short: 'KY',
		iso_code: 'CYM',
	},
	{
		country_name: 'Central African Republic',
		country_code: '236',
		iso_code_short: 'CF',
		iso_code: 'CAF',
	},
	{
		country_name: 'Chad',
		country_code: '235',
		iso_code_short: 'TD',
		iso_code: 'TCD',
	},
	{
		country_name: 'Chile',
		country_code: '56',
		iso_code_short: 'CL',
		iso_code: 'CHL',
	},
	{
		country_name: 'China',
		country_code: '86',
		iso_code_short: 'CN',
		iso_code: 'CHN',
	},
	{
		country_name: 'Christmas Island',
		country_code: '61',
		iso_code_short: 'CX',
		iso_code: 'CXR',
	},
	{
		country_name: 'Cocos Islands',
		country_code: '61',
		iso_code_short: 'CC',
		iso_code: 'CCK',
	},
	{
		country_name: 'Colombia',
		country_code: '57',
		iso_code_short: 'CO',
		iso_code: 'COL',
	},
	{
		country_name: 'Comoros',
		country_code: '269',
		iso_code_short: 'KM',
		iso_code: 'COM',
	},
	{
		country_name: 'Cook Islands',
		country_code: '682',
		iso_code_short: 'CK',
		iso_code: 'COK',
	},
	{
		country_name: 'Costa Rica',
		country_code: '506',
		iso_code_short: 'CR',
		iso_code: 'CRI',
	},
	{
		country_name: 'Croatia',
		country_code: '385',
		iso_code_short: 'HR',
		iso_code: 'HRV',
	},
	{
		country_name: 'Cuba',
		country_code: '53',
		iso_code_short: 'CU',
		iso_code: 'CUB',
	},
	{
		country_name: 'Curacao',
		country_code: '599',
		iso_code_short: 'CW',
		iso_code: 'CUW',
	},
	{
		country_name: 'Cyprus',
		country_code: '357',
		iso_code_short: 'CY',
		iso_code: 'CYP',
	},
	{
		country_name: 'Czech Republic',
		country_code: '420',
		iso_code_short: 'CZ',
		iso_code: 'CZE',
	},
	{
		country_name: 'Democratic Republic of the Congo',
		country_code: '243',
		iso_code_short: 'CD',
		iso_code: 'COD',
	},
	{
		country_name: 'Denmark',
		country_code: '45',
		iso_code_short: 'DK',
		iso_code: 'DNK',
	},
	{
		country_name: 'Djibouti',
		country_code: '253',
		iso_code_short: 'DJ',
		iso_code: 'DJI',
	},
	{
		country_name: 'Dominica',
		country_code: '1-767',
		iso_code_short: 'DM',
		iso_code: 'DMA',
	},
	{
		country_name: 'Dominican Republic',
		country_code: '1-809, 1-829, 1-849',
		iso_code_short: 'DO',
		iso_code: 'DOM',
	},
	{
		country_name: 'East Timor',
		country_code: '670',
		iso_code_short: 'TL',
		iso_code: 'TLS',
	},
	{
		country_name: 'Ecuador',
		country_code: '593',
		iso_code_short: 'EC',
		iso_code: 'ECU',
	},
	{
		country_name: 'Egypt',
		country_code: '20',
		iso_code_short: 'EG',
		iso_code: 'EGY',
	},
	{
		country_name: 'El Salvador',
		country_code: '503',
		iso_code_short: 'SV',
		iso_code: 'SLV',
	},
	{
		country_name: 'Equatorial Guinea',
		country_code: '240',
		iso_code_short: 'GQ',
		iso_code: 'GNQ',
	},
	{
		country_name: 'Eritrea',
		country_code: '291',
		iso_code_short: 'ER',
		iso_code: 'ERI',
	},
	{
		country_name: 'Estonia',
		country_code: '372',
		iso_code_short: 'EE',
		iso_code: 'EST',
	},
	{
		country_name: 'Ethiopia',
		country_code: '251',
		iso_code_short: 'ET',
		iso_code: 'ETH',
	},
	{
		country_name: 'Falkland Islands',
		country_code: '500',
		iso_code_short: 'FK',
		iso_code: 'FLK',
	},
	{
		country_name: 'Faroe Islands',
		country_code: '298',
		iso_code_short: 'FO',
		iso_code: 'FRO',
	},
	{
		country_name: 'Fiji',
		country_code: '679',
		iso_code_short: 'FJ',
		iso_code: 'FJI',
	},
	{
		country_name: 'Finland',
		country_code: '358',
		iso_code_short: 'FI',
		iso_code: 'FIN',
	},
	{
		country_name: 'France',
		country_code: '33',
		iso_code_short: 'FR',
		iso_code: 'FRA',
	},
	{
		country_name: 'French Polynesia',
		country_code: '689',
		iso_code_short: 'PF',
		iso_code: 'PYF',
	},
	{
		country_name: 'Gabon',
		country_code: '241',
		iso_code_short: 'GA',
		iso_code: 'GAB',
	},
	{
		country_name: 'Gambia',
		country_code: '220',
		iso_code_short: 'GM',
		iso_code: 'GMB',
	},
	{
		country_name: 'Georgia',
		country_code: '995',
		iso_code_short: 'GE',
		iso_code: 'GEO',
	},
	{
		country_name: 'Germany',
		country_code: '49',
		iso_code_short: 'DE',
		iso_code: 'DEU',
	},
	{
		country_name: 'Ghana',
		country_code: '233',
		iso_code_short: 'GH',
		iso_code: 'GHA',
	},
	{
		country_name: 'Gibraltar',
		country_code: '350',
		iso_code_short: 'GI',
		iso_code: 'GIB',
	},
	{
		country_name: 'Greece',
		country_code: '30',
		iso_code_short: 'GR',
		iso_code: 'GRC',
	},
	{
		country_name: 'Greenland',
		country_code: '299',
		iso_code_short: 'GL',
		iso_code: 'GRL',
	},
	{
		country_name: 'Grenada',
		country_code: '1-473',
		iso_code_short: 'GD',
		iso_code: 'GRD',
	},
	{
		country_name: 'Guam',
		country_code: '1-671',
		iso_code_short: 'GU',
		iso_code: 'GUM',
	},
	{
		country_name: 'Guatemala',
		country_code: '502',
		iso_code_short: 'GT',
		iso_code: 'GTM',
	},
	{
		country_name: 'Guernsey',
		country_code: '44-1481',
		iso_code_short: 'GG',
		iso_code: 'GGY',
	},
	{
		country_name: 'Guinea',
		country_code: '224',
		iso_code_short: 'GN',
		iso_code: 'GIN',
	},
	{
		country_name: 'Guinea-Bissau',
		country_code: '245',
		iso_code_short: 'GW',
		iso_code: 'GNB',
	},
	{
		country_name: 'Guyana',
		country_code: '592',
		iso_code_short: 'GY',
		iso_code: 'GUY',
	},
	{
		country_name: 'Haiti',
		country_code: '509',
		iso_code_short: 'HT',
		iso_code: 'HTI',
	},
	{
		country_name: 'Honduras',
		country_code: '504',
		iso_code_short: 'HN',
		iso_code: 'HND',
	},
	{
		country_name: 'Hong Kong',
		country_code: '852',
		iso_code_short: 'HK',
		iso_code: 'HKG',
	},
	{
		country_name: 'Hungary',
		country_code: '36',
		iso_code_short: 'HU',
		iso_code: 'HUN',
	},
	{
		country_name: 'Iceland',
		country_code: '354',
		iso_code_short: 'IS',
		iso_code: 'ISL',
	},
	{
		country_name: 'India',
		country_code: '91',
		iso_code_short: 'IN',
		iso_code: 'IND',
	},
	{
		country_name: 'Indonesia',
		country_code: '62',
		iso_code_short: 'ID',
		iso_code: 'IDN',
	},
	{
		country_name: 'Iran',
		country_code: '98',
		iso_code_short: 'IR',
		iso_code: 'IRN',
	},
	{
		country_name: 'Iraq',
		country_code: '964',
		iso_code_short: 'IQ',
		iso_code: 'IRQ',
	},
	{
		country_name: 'Ireland',
		country_code: '353',
		iso_code_short: 'IE',
		iso_code: 'IRL',
	},
	{
		country_name: 'Isle of Man',
		country_code: '44-1624',
		iso_code_short: 'IM',
		iso_code: 'IMN',
	},
	{
		country_name: 'Israel',
		country_code: '972',
		iso_code_short: 'IL',
		iso_code: 'ISR',
	},
	{
		country_name: 'Italy',
		country_code: '39',
		iso_code_short: 'IT',
		iso_code: 'ITA',
	},
	{
		country_name: 'Ivory Coast',
		country_code: '225',
		iso_code_short: 'CI',
		iso_code: 'CIV',
	},
	{
		country_name: 'Jamaica',
		country_code: '1-876',
		iso_code_short: 'JM',
		iso_code: 'JAM',
	},
	{
		country_name: 'Japan',
		country_code: '81',
		iso_code_short: 'JP',
		iso_code: 'JPN',
	},
	{
		country_name: 'Jersey',
		country_code: '44-1534',
		iso_code_short: 'JE',
		iso_code: 'JEY',
	},
	{
		country_name: 'Jordan',
		country_code: '962',
		iso_code_short: 'JO',
		iso_code: 'JOR',
	},
	{
		country_name: 'Kazakhstan',
		country_code: '7',
		iso_code_short: 'KZ',
		iso_code: 'KAZ',
	},
	{
		country_name: 'Kenya',
		country_code: '254',
		iso_code_short: 'KE',
		iso_code: 'KEN',
	},
	{
		country_name: 'Kiribati',
		country_code: '686',
		iso_code_short: 'KI',
		iso_code: 'KIR',
	},
	{
		country_name: 'Kosovo',
		country_code: '383',
		iso_code_short: 'XK',
		iso_code: 'XKX',
	},
	{
		country_name: 'Kuwait',
		country_code: '965',
		iso_code_short: 'KW',
		iso_code: 'KWT',
	},
	{
		country_name: 'Kyrgyzstan',
		country_code: '996',
		iso_code_short: 'KG',
		iso_code: 'KGZ',
	},
	{
		country_name: 'Laos',
		country_code: '856',
		iso_code_short: 'LA',
		iso_code: 'LAO',
	},
	{
		country_name: 'Latvia',
		country_code: '371',
		iso_code_short: 'LV',
		iso_code: 'LVA',
	},
	{
		country_name: 'Lebanon',
		country_code: '961',
		iso_code_short: 'LB',
		iso_code: 'LBN',
	},
	{
		country_name: 'Lesotho',
		country_code: '266',
		iso_code_short: 'LS',
		iso_code: 'LSO',
	},
	{
		country_name: 'Liberia',
		country_code: '231',
		iso_code_short: 'LR',
		iso_code: 'LBR',
	},
	{
		country_name: 'Libya',
		country_code: '218',
		iso_code_short: 'LY',
		iso_code: 'LBY',
	},
	{
		country_name: 'Liechtenstein',
		country_code: '423',
		iso_code_short: 'LI',
		iso_code: 'LIE',
	},
	{
		country_name: 'Lithuania',
		country_code: '370',
		iso_code_short: 'LT',
		iso_code: 'LTU',
	},
	{
		country_name: 'Luxembourg',
		country_code: '352',
		iso_code_short: 'LU',
		iso_code: 'LUX',
	},
	{
		country_name: 'Macau',
		country_code: '853',
		iso_code_short: 'MO',
		iso_code: 'MAC',
	},
	{
		country_name: 'Macedonia',
		country_code: '389',
		iso_code_short: 'MK',
		iso_code: 'MKD',
	},
	{
		country_name: 'Madagascar',
		country_code: '261',
		iso_code_short: 'MG',
		iso_code: 'MDG',
	},
	{
		country_name: 'Malawi',
		country_code: '265',
		iso_code_short: 'MW',
		iso_code: 'MWI',
	},
	{
		country_name: 'Malaysia',
		country_code: '60',
		iso_code_short: 'MY',
		iso_code: 'MYS',
	},
	{
		country_name: 'Maldives',
		country_code: '960',
		iso_code_short: 'MV',
		iso_code: 'MDV',
	},
	{
		country_name: 'Mali',
		country_code: '223',
		iso_code_short: 'ML',
		iso_code: 'MLI',
	},
	{
		country_name: 'Malta',
		country_code: '356',
		iso_code_short: 'MT',
		iso_code: 'MLT',
	},
	{
		country_name: 'Marshall Islands',
		country_code: '692',
		iso_code_short: 'MH',
		iso_code: 'MHL',
	},
	{
		country_name: 'Mauritania',
		country_code: '222',
		iso_code_short: 'MR',
		iso_code: 'MRT',
	},
	{
		country_name: 'Mauritius',
		country_code: '230',
		iso_code_short: 'MU',
		iso_code: 'MUS',
	},
	{
		country_name: 'Mayotte',
		country_code: '262',
		iso_code_short: 'YT',
		iso_code: 'MYT',
	},
	{
		country_name: 'Mexico',
		country_code: '52',
		iso_code_short: 'MX',
		iso_code: 'MEX',
	},
	{
		country_name: 'Micronesia',
		country_code: '691',
		iso_code_short: 'FM',
		iso_code: 'FSM',
	},
	{
		country_name: 'Moldova',
		country_code: '373',
		iso_code_short: 'MD',
		iso_code: 'MDA',
	},
	{
		country_name: 'Monaco',
		country_code: '377',
		iso_code_short: 'MC',
		iso_code: 'MCO',
	},
	{
		country_name: 'Mongolia',
		country_code: '976',
		iso_code_short: 'MN',
		iso_code: 'MNG',
	},
	{
		country_name: 'Montenegro',
		country_code: '382',
		iso_code_short: 'ME',
		iso_code: 'MNE',
	},
	{
		country_name: 'Montserrat',
		country_code: '1-664',
		iso_code_short: 'MS',
		iso_code: 'MSR',
	},
	{
		country_name: 'Morocco',
		country_code: '212',
		iso_code_short: 'MA',
		iso_code: 'MAR',
	},
	{
		country_name: 'Mozambique',
		country_code: '258',
		iso_code_short: 'MZ',
		iso_code: 'MOZ',
	},
	{
		country_name: 'Myanmar',
		country_code: '95',
		iso_code_short: 'MM',
		iso_code: 'MMR',
	},
	{
		country_name: 'Namibia',
		country_code: '264',
		iso_code_short: 'NA',
		iso_code: 'NAM',
	},
	{
		country_name: 'Nauru',
		country_code: '674',
		iso_code_short: 'NR',
		iso_code: 'NRU',
	},
	{
		country_name: 'Nepal',
		country_code: '977',
		iso_code_short: 'NP',
		iso_code: 'NPL',
	},
	{
		country_name: 'Netherlands',
		country_code: '31',
		iso_code_short: 'NL',
		iso_code: 'NLD',
	},
	{
		country_name: 'Netherlands Antilles',
		country_code: '599',
		iso_code_short: 'AN',
		iso_code: 'ANT',
	},
	{
		country_name: 'New Caledonia',
		country_code: '687',
		iso_code_short: 'NC',
		iso_code: 'NCL',
	},
	{
		country_name: 'New Zealand',
		country_code: '64',
		iso_code_short: 'NZ',
		iso_code: 'NZL',
	},
	{
		country_name: 'Nicaragua',
		country_code: '505',
		iso_code_short: 'NI',
		iso_code: 'NIC',
	},
	{
		country_name: 'Niger',
		country_code: '227',
		iso_code_short: 'NE',
		iso_code: 'NER',
	},
	{
		country_name: 'Nigeria',
		country_code: '234',
		iso_code_short: 'NG',
		iso_code: 'NGA',
	},
	{
		country_name: 'Niue',
		country_code: '683',
		iso_code_short: 'NU',
		iso_code: 'NIU',
	},
	{
		country_name: 'North Korea',
		country_code: '850',
		iso_code_short: 'KP',
		iso_code: 'PRK',
	},
	{
		country_name: 'Northern Mariana Islands',
		country_code: '1-670',
		iso_code_short: 'MP',
		iso_code: 'MNP',
	},
	{
		country_name: 'Norway',
		country_code: '47',
		iso_code_short: 'NO',
		iso_code: 'NOR',
	},
	{
		country_name: 'Oman',
		country_code: '968',
		iso_code_short: 'OM',
		iso_code: 'OMN',
	},
	{
		country_name: 'Pakistan',
		country_code: '92',
		iso_code_short: 'PK',
		iso_code: 'PAK',
	},
	{
		country_name: 'Palau',
		country_code: '680',
		iso_code_short: 'PW',
		iso_code: 'PLW',
	},
	{
		country_name: 'Palestine',
		country_code: '970',
		iso_code_short: 'PS',
		iso_code: 'PSE',
	},
	{
		country_name: 'Panama',
		country_code: '507',
		iso_code_short: 'PA',
		iso_code: 'PAN',
	},
	{
		country_name: 'Papua New Guinea',
		country_code: '675',
		iso_code_short: 'PG',
		iso_code: 'PNG',
	},
	{
		country_name: 'Paraguay',
		country_code: '595',
		iso_code_short: 'PY',
		iso_code: 'PRY',
	},
	{
		country_name: 'Peru',
		country_code: '51',
		iso_code_short: 'PE',
		iso_code: 'PER',
	},
	{
		country_name: 'Philippines',
		country_code: '63',
		iso_code_short: 'PH',
		iso_code: 'PHL',
	},
	{
		country_name: 'Pitcairn',
		country_code: '64',
		iso_code_short: 'PN',
		iso_code: 'PCN',
	},
	{
		country_name: 'Poland',
		country_code: '48',
		iso_code_short: 'PL',
		iso_code: 'POL',
	},
	{
		country_name: 'Portugal',
		country_code: '351',
		iso_code_short: 'PT',
		iso_code: 'PRT',
	},
	{
		country_name: 'Puerto Rico',
		country_code: '1-787, 1-939',
		iso_code_short: 'PR',
		iso_code: 'PRI',
	},
	{
		country_name: 'Qatar',
		country_code: '974',
		iso_code_short: 'QA',
		iso_code: 'QAT',
	},
	{
		country_name: 'Republic of the Congo',
		country_code: '242',
		iso_code_short: 'CG',
		iso_code: 'COG',
	},
	{
		country_name: 'Reunion',
		country_code: '262',
		iso_code_short: 'RE',
		iso_code: 'REU',
	},
	{
		country_name: 'Romania',
		country_code: '40',
		iso_code_short: 'RO',
		iso_code: 'ROU',
	},
	{
		country_name: 'Russia',
		country_code: '7',
		iso_code_short: 'RU',
		iso_code: 'RUS',
	},
	{
		country_name: 'Rwanda',
		country_code: '250',
		iso_code_short: 'RW',
		iso_code: 'RWA',
	},
	{
		country_name: 'Saint Barthelemy',
		country_code: '590',
		iso_code_short: 'BL',
		iso_code: 'BLM',
	},
	{
		country_name: 'Saint Helena',
		country_code: '290',
		iso_code_short: 'SH',
		iso_code: 'SHN',
	},
	{
		country_name: 'Saint Kitts and Nevis',
		country_code: '1-869',
		iso_code_short: 'KN',
		iso_code: 'KNA',
	},
	{
		country_name: 'Saint Lucia',
		country_code: '1-758',
		iso_code_short: 'LC',
		iso_code: 'LCA',
	},
	{
		country_name: 'Saint Martin',
		country_code: '590',
		iso_code_short: 'MF',
		iso_code: 'MAF',
	},
	{
		country_name: 'Saint Pierre and Miquelon',
		country_code: '508',
		iso_code_short: 'PM',
		iso_code: 'SPM',
	},
	{
		country_name: 'Saint Vincent and the Grenadines',
		country_code: '1-784',
		iso_code_short: 'VC',
		iso_code: 'VCT',
	},
	{
		country_name: 'Samoa',
		country_code: '685',
		iso_code_short: 'WS',
		iso_code: 'WSM',
	},
	{
		country_name: 'San Marino',
		country_code: '378',
		iso_code_short: 'SM',
		iso_code: 'SMR',
	},
	{
		country_name: 'Sao Tome and Principe',
		country_code: '239',
		iso_code_short: 'ST',
		iso_code: 'STP',
	},
	{
		country_name: 'Saudi Arabia',
		country_code: '966',
		iso_code_short: 'SA',
		iso_code: 'SAU',
	},
	{
		country_name: 'Senegal',
		country_code: '221',
		iso_code_short: 'SN',
		iso_code: 'SEN',
	},
	{
		country_name: 'Serbia',
		country_code: '381',
		iso_code_short: 'RS',
		iso_code: 'SRB',
	},
	{
		country_name: 'Seychelles',
		country_code: '248',
		iso_code_short: 'SC',
		iso_code: 'SYC',
	},
	{
		country_name: 'Sierra Leone',
		country_code: '232',
		iso_code_short: 'SL',
		iso_code: 'SLE',
	},
	{
		country_name: 'Singapore',
		country_code: '65',
		iso_code_short: 'SG',
		iso_code: 'SGP',
	},
	{
		country_name: 'Sint Maarten',
		country_code: '1-721',
		iso_code_short: 'SX',
		iso_code: 'SXM',
	},
	{
		country_name: 'Slovakia',
		country_code: '421',
		iso_code_short: 'SK',
		iso_code: 'SVK',
	},
	{
		country_name: 'Slovenia',
		country_code: '386',
		iso_code_short: 'SI',
		iso_code: 'SVN',
	},
	{
		country_name: 'Solomon Islands',
		country_code: '677',
		iso_code_short: 'SB',
		iso_code: 'SLB',
	},
	{
		country_name: 'Somalia',
		country_code: '252',
		iso_code_short: 'SO',
		iso_code: 'SOM',
	},
	{
		country_name: 'South Africa',
		country_code: '27',
		iso_code_short: 'ZA',
		iso_code: 'ZAF',
	},
	{
		country_name: 'South Korea',
		country_code: '82',
		iso_code_short: 'KR',
		iso_code: 'KOR',
	},
	{
		country_name: 'South Sudan',
		country_code: '211',
		iso_code_short: 'SS',
		iso_code: 'SSD',
	},
	{
		country_name: 'Spain',
		country_code: '34',
		iso_code_short: 'ES',
		iso_code: 'ESP',
	},
	{
		country_name: 'Sri Lanka',
		country_code: '94',
		iso_code_short: 'LK',
		iso_code: 'LKA',
	},
	{
		country_name: 'Sudan',
		country_code: '249',
		iso_code_short: 'SD',
		iso_code: 'SDN',
	},
	{
		country_name: 'Suriname',
		country_code: '597',
		iso_code_short: 'SR',
		iso_code: 'SUR',
	},
	{
		country_name: 'Svalbard and Jan Mayen',
		country_code: '47',
		iso_code_short: 'SJ',
		iso_code: 'SJM',
	},
	{
		country_name: 'Swaziland',
		country_code: '268',
		iso_code_short: 'SZ',
		iso_code: 'SWZ',
	},
	{
		country_name: 'Sweden',
		country_code: '46',
		iso_code_short: 'SE',
		iso_code: 'SWE',
	},
	{
		country_name: 'Switzerland',
		country_code: '41',
		iso_code_short: 'CH',
		iso_code: 'CHE',
	},
	{
		country_name: 'Syria',
		country_code: '963',
		iso_code_short: 'SY',
		iso_code: 'SYR',
	},
	{
		country_name: 'Taiwan',
		country_code: '886',
		iso_code_short: 'TW',
		iso_code: 'TWN',
	},
	{
		country_name: 'Tajikistan',
		country_code: '992',
		iso_code_short: 'TJ',
		iso_code: 'TJK',
	},
	{
		country_name: 'Tanzania',
		country_code: '255',
		iso_code_short: 'TZ',
		iso_code: 'TZA',
	},
	{
		country_name: 'Thailand',
		country_code: '66',
		iso_code_short: 'TH',
		iso_code: 'THA',
	},
	{
		country_name: 'Togo',
		country_code: '228',
		iso_code_short: 'TG',
		iso_code: 'TGO',
	},
	{
		country_name: 'Tokelau',
		country_code: '690',
		iso_code_short: 'TK',
		iso_code: 'TKL',
	},
	{
		country_name: 'Tonga',
		country_code: '676',
		iso_code_short: 'TO',
		iso_code: 'TON',
	},
	{
		country_name: 'Trinidad and Tobago',
		country_code: '1-868',
		iso_code_short: 'TT',
		iso_code: 'TTO',
	},
	{
		country_name: 'Tunisia',
		country_code: '216',
		iso_code_short: 'TN',
		iso_code: 'TUN',
	},
	{
		country_name: 'Turkey',
		country_code: '90',
		iso_code_short: 'TR',
		iso_code: 'TUR',
	},
	{
		country_name: 'Turkmenistan',
		country_code: '993',
		iso_code_short: 'TM',
		iso_code: 'TKM',
	},
	{
		country_name: 'Turks and Caicos Islands',
		country_code: '1-649',
		iso_code_short: 'TC',
		iso_code: 'TCA',
	},
	{
		country_name: 'Tuvalu',
		country_code: '688',
		iso_code_short: 'TV',
		iso_code: 'TUV',
	},
	{
		country_name: 'U.S. Virgin Islands',
		country_code: '1-340',
		iso_code_short: 'VI',
		iso_code: 'VIR',
	},
	{
		country_name: 'Uganda',
		country_code: '256',
		iso_code_short: 'UG',
		iso_code: 'UGA',
	},
	{
		country_name: 'Ukraine',
		country_code: '380',
		iso_code_short: 'UA',
		iso_code: 'UKR',
	},
	{
		country_name: 'United Arab Emirates',
		country_code: '971',
		iso_code_short: 'AE',
		iso_code: 'ARE',
	},
	{
		country_name: 'United Kingdom',
		country_code: '44',
		iso_code_short: 'GB',
		iso_code: 'GBR',
	},
	{
		country_name: 'United States',
		country_code: '1',
		iso_code_short: 'US',
		iso_code: 'USA',
	},
	{
		country_name: 'Uruguay',
		country_code: '598',
		iso_code_short: 'UY',
		iso_code: 'URY',
	},
	{
		country_name: 'Uzbekistan',
		country_code: '998',
		iso_code_short: 'UZ',
		iso_code: 'UZB',
	},
	{
		country_name: 'Vanuatu',
		country_code: '678',
		iso_code_short: 'VU',
		iso_code: 'VUT',
	},
	{
		country_name: 'Vatican',
		country_code: '379',
		iso_code_short: 'VA',
		iso_code: 'VAT',
	},
	{
		country_name: 'Venezuela',
		country_code: '58',
		iso_code_short: 'VE',
		iso_code: 'VEN',
	},
	{
		country_name: 'Vietnam',
		country_code: '84',
		iso_code_short: 'VN',
		iso_code: 'VNM',
	},
	{
		country_name: 'Wallis and Futuna',
		country_code: '681',
		iso_code_short: 'WF',
		iso_code: 'WLF',
	},
	{
		country_name: 'Western Sahara',
		country_code: '212',
		iso_code_short: 'EH',
		iso_code: 'ESH',
	},
	{
		country_name: 'Yemen',
		country_code: '967',
		iso_code_short: 'YE',
		iso_code: 'YEM',
	},
	{
		country_name: 'Zambia',
		country_code: '260',
		iso_code_short: 'ZM',
		iso_code: 'ZMB',
	},
	{
		country_name: 'Zimbabwe',
		country_code: '263',
		iso_code_short: 'ZW',
		iso_code: 'ZWE',
	},
] as const);
