// ! Auto-generated by scripts/generate-types.mjs — DO NOT EDIT
// ? Derived from package.json exports. Regenerate with: node scripts/generate-types.mjs

import * as Toolbox from 'toolbox-x';
import * as ChangeCase from 'toolbox-x/change-case';
import * as Colors from 'toolbox-x/colors';
import * as Constants from 'toolbox-x/constants';
import * as Converter from 'toolbox-x/converter';
import * as ToolboxDate from 'toolbox-x/date';
import * as Dom from 'toolbox-x/dom';
import * as Guards from 'toolbox-x/guards';
import * as Hash from 'toolbox-x/hash';
import * as HttpStatus from 'toolbox-x/http-status';
import * as Paginator from 'toolbox-x/paginator';
import * as Stylog from 'toolbox-x/stylog';
import * as Types from 'toolbox-x/types';
import * as TypesArray from 'toolbox-x/types/array';
import * as TypesColors from 'toolbox-x/types/colors';
import * as TypesConverter from 'toolbox-x/types/converter';
import * as TypesDate from 'toolbox-x/types/date';
import * as TypesForm from 'toolbox-x/types/form';
import * as TypesHash from 'toolbox-x/types/hash';
import * as TypesHttpStatus from 'toolbox-x/types/http-status';
import * as TypesNumber from 'toolbox-x/types/number';
import * as TypesObject from 'toolbox-x/types/object';
import * as TypesPluralizer from 'toolbox-x/types/pluralizer';
import * as TypesString from 'toolbox-x/types/string';
import * as TypesStylog from 'toolbox-x/types/stylog';
import * as TypesUtils from 'toolbox-x/types/utils';
import * as TypesVerbalizer from 'toolbox-x/types/verbalizer';
import * as Verbalizer from 'toolbox-x/verbalizer';

type ToolboxModule = 'toolbox-x' | `toolbox-x/${string}`;

export const MODULES: Record<ToolboxModule, unknown> = {
	'toolbox-x': Toolbox,
	'toolbox-x/change-case': ChangeCase,
	'toolbox-x/colors': Colors,
	'toolbox-x/constants': Constants,
	'toolbox-x/converter': Converter,
	'toolbox-x/date': ToolboxDate,
	'toolbox-x/dom': Dom,
	'toolbox-x/guards': Guards,
	'toolbox-x/hash': Hash,
	'toolbox-x/http-status': HttpStatus,
	'toolbox-x/paginator': Paginator,
	'toolbox-x/stylog': Stylog,
	'toolbox-x/types': Types,
	'toolbox-x/types/array': TypesArray,
	'toolbox-x/types/colors': TypesColors,
	'toolbox-x/types/converter': TypesConverter,
	'toolbox-x/types/date': TypesDate,
	'toolbox-x/types/form': TypesForm,
	'toolbox-x/types/hash': TypesHash,
	'toolbox-x/types/http-status': TypesHttpStatus,
	'toolbox-x/types/number': TypesNumber,
	'toolbox-x/types/object': TypesObject,
	'toolbox-x/types/pluralizer': TypesPluralizer,
	'toolbox-x/types/string': TypesString,
	'toolbox-x/types/stylog': TypesStylog,
	'toolbox-x/types/utils': TypesUtils,
	'toolbox-x/types/verbalizer': TypesVerbalizer,
	'toolbox-x/verbalizer': Verbalizer,
};

export { Toolbox, type ToolboxModule };
