/** Record of Units (Categorized) */
export const UNITS = /* @__PURE__ */ Object.freeze({
	time: [
		'nanosecond',
		'microsecond',
		'millisecond',
		'second',
		'minute',
		'hour',
		'day',
		'week',
		'month',
		'year',
		'decade',
		'century',
		'millennium',
	],
	length: [
		'millimeter',
		'centimeter',
		'meter',
		'kilometer',
		'millimetre',
		'centimetre',
		'metre',
		'kilometre',
		'inch',
		'foot',
		'yard',
		'mile',
		'nautical-mile',
		'light-year',
	],
	data: [
		'bit',
		'byte',
		'kilobit',
		'kilobyte',
		'megabit',
		'megabyte',
		'gigabit',
		'gigabyte',
		'terabit',
		'terabyte',
		'petabit',
		'petabyte',
	],
	temp: ['celsius', 'fahrenheit', 'kelvin'],
	area: [
		'square-millimeter',
		'square-centimeter',
		'square-meter',
		'square-kilometer',
		'square-millimetre',
		'square-centimetre',
		'square-metre',
		'square-kilometre',
		'square-inch',
		'square-foot',
		'square-yard',
		'square-mile',
		'hectare',
		'acre',
	],
	volume: [
		'cubic-millimeter',
		'cubic-centimeter',
		'cubic-meter',
		'cubic-kilometer',
		'cubic-millimetre',
		'cubic-centimetre',
		'cubic-metre',
		'cubic-kilometre',
		'cubic-inch',
		'cubic-foot',
		'cubic-yard',
		'liter',
		'litre',
		'milliliter',
		'millilitre',
		'gallon',
		'quart',
		'pint',
		'cup',
		'tablespoon',
		'teaspoon',
	],
	mass: [
		'microgram',
		'milligram',
		'gram',
		'kilogram',
		'tonne',
		'ounce',
		'pound',
		'stone',
		'short-ton',
		'long-ton',
	],
} as const);

export const IRREGULAR_PLURALS = /* @__PURE__ */ Object.freeze({
	millennium: 'millennia',
	century: 'centuries',
} as Record<string, string>);

export const INVARIANT_UNITS = /* @__PURE__ */ Object.freeze(
	new Set(['celsius', 'fahrenheit', 'kelvin'])
);

export const Y_TO_IES = /* @__PURE__ */ Object.freeze(new Set(['century']));
